name: JSON Checker

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Show Swift version
      run: swift --version
    - name: Run
      run: swift run -v
      working-directory: ./Tools/Checker